### ISSUE TITLE
Modern datasets

### ISSUE THREAD

**Issue by BaltashovIlia** [Yvanali/Deep-Learning-for-LiDAR-Point-Clouds#1]
Hi, 
Good job. It’s the best list of 3d object detection articles which I have found.  

Please add modern datasets, which include 3D detection task, to your list: 
1. nuScenes https://www.nuscenes.org/object-detection?externalData=all&mapData=all&modalities=Any
2. Waymo https://waymo.com/open/ (you need a google account to get access to leaderboard)
3. Lyft https://level5.lyft.com/dataset/ 
4. apolloscape http://apolloscape.auto/leader_board.html 

And here is a good survey article, witch includes classification of 3D point cloud based detection algorithms:  
https://arxiv.org/abs/1912.12033 

It will also be nice if you rename the repository to something like awesome-3d-object-detection. It will be easier to find, because usually such lists are called awesome-…..

**Comment by Yvanali** [comment]
@BaltashovIlia Thanks for your valuable suggestion. I have added the above datasets in our repository and rename the repository to make it easier to find.

As for the review papers, we will make a table for conclusion in the future.
